### ISSUE TITLE
[TRACKER] Improvements for the next mmm release

### ISSUE THREAD

**Issue by MrKevinWeiss** [riot-appstore/memory_map_manager#29]
- [ ] Support enums
- [ ] Incorporate access levels more than numbers
- [ ] use config file for generation parameters
- [ ] Defaults generated at runtime

**Comment by MrKevinWeiss** [comment]
Issue with the generation helpers having an extra `"` at the end
